-- MySQL Script generated by MySQL Workbench
-- 11/11/15 14:38:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bookmaker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookmaker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookmaker` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bookmaker` ;

-- -----------------------------------------------------
-- Table `bookmaker`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmaker`.`user` ;

CREATE TABLE IF NOT EXISTS `bookmaker`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `firstname` VARCHAR(45) NULL COMMENT '',
  `isAdmin` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`, `username`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmaker`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmaker`.`game` ;

CREATE TABLE IF NOT EXISTS `bookmaker`.`game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userId` INT NULL COMMENT '',
  `start` DATETIME(6) NOT NULL COMMENT '',
  `team1` VARCHAR(45) NULL COMMENT '',
  `team2` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmaker`.`betGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmaker`.`betGame` ;

CREATE TABLE IF NOT EXISTS `bookmaker`.`betGame` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `game_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_id`, `game_id`)  COMMENT '',
  INDEX `fk_bet_user_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_bet_game1_idx` (`game_id` ASC)  COMMENT '',
  CONSTRAINT `fk_bet_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bookmaker`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bet_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `bookmaker`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmaker`.`conditionsPerGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmaker`.`conditionsPerGame` ;

CREATE TABLE IF NOT EXISTS `bookmaker`.`conditionsPerGame` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `game_id` INT UNSIGNED NOT NULL COMMENT '',
  `text_id` INT UNSIGNED NULL COMMENT '',
  `odd1` FLOAT NULL COMMENT '',
  `odd2` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id`, `game_id`)  COMMENT '',
  INDEX `fk_conditionsPerGame_game1_idx` (`game_id` ASC)  COMMENT '',
  CONSTRAINT `fk_conditionsPerGame_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `bookmaker`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookmaker`.`bet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookmaker`.`bet` ;

CREATE TABLE IF NOT EXISTS `bookmaker`.`bet` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `betGame_id` INT UNSIGNED NOT NULL COMMENT '',
  `cond_id` INT UNSIGNED NOT NULL COMMENT '',
  `bet` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id`, `betGame_id`, `cond_id`)  COMMENT '',
  INDEX `fk_bet_conditionsPerGame2_idx` (`cond_id` ASC)  COMMENT '',
  INDEX `fk_bet_betGame1_idx` (`betGame_id` ASC)  COMMENT '',
  CONSTRAINT `fk_bet_conditionsPerGame2`
    FOREIGN KEY (`cond_id`)
    REFERENCES `bookmaker`.`conditionsPerGame` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bet_betGame1`
    FOREIGN KEY (`betGame_id`)
    REFERENCES `bookmaker`.`betGame` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
